### ISSUE TITLE
ImportError: /usr/local/lib/python2.7/dis undefined symbol: py_callback

### ISSUE THREAD

**Issue by arshpreetsingh** [smvv/pybison#1]
I am getting following error while Running "python -c import bison"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/bison.py", line 23, in <module>
    from bison_ import ParserEngine
ImportError: /usr/local/lib/python2.7/dist-packages/bison_.so: undefined symbol: py_callback

**Comment by smvv** [comment]
Since I was using PyBison directly as a git submodule, I did not use the setup.py script at all. I've fixed the setup.py script in the latest commit. Thanks for submitting the error!

**Comment by smvv** [comment]
(BTW We've used PyBison extensively in an automatic term rewriting system. So, if you're looking for a large example how to use PyBison, see: https://github.com/smvv/trs)

**Comment by arshpreetsingh** [comment]
Thanks a lot! I used Bison but I am very limited with C++, So was looking for something with Python, I want to use Pybison for parsing IFC(industry foundation classes) files, basically raw idea is to convert IFC file into C++ classes which will be understood by open-cascade geometry engine. Thanks for telling about TRS.
