### ISSUE TITLE
Error when reporting parser errors

### ISSUE THREAD

**Issue by arquer** [smvv/pybison#10]
Hello,

I have been using pybison for some days now and I have come across what I believe is a "bug". 

The issue appears whenever the parser throws an error. For example, when I try to parse a file with a syntax error I get the following:

> Traceback (most recent call last):
  File "./run_parser.py", line 15, in <module>
    sv_parser.run(read = file_input.read)
  File "<path>/bison/__init__.py", line 264, in run
    self.report_last_error(filename, e)
  File "<path>/bison/__init__.py", line 340, in report_last_error
    if not self.interactive:
AttributeError: 'SystemVerilogParser' object has no attribute 'interactive'

if I go to the line where the error is reported this is what is there: 
`        if not self.interactive:
            raise

        if self.verbose:
            traceback.print_exc()

        print 'ERROR:', error
`

Apparently the function report_last_error() tries to check the value of self.interactive, however I see no reference to an attribute called "interactive" anywhere before.

I worked around the issue by declaring an "interactive" attribute in my parser subclass with value True/False. I don't know if this was the original intent and this is just not explained in the documentation (or at least I have not seen it) or if this attribute is suposed to be declared inside BisonParser itself.

**Comment by smvv** [comment]
That's indeed a bug. I think that adding ``self.interactive = False`` on this line https://github.com/smvv/pybison/blob/61e82ab4888710eb9b9f4e1d9f286bfda328b1c4/src/python/__init__.py#L157 should fix the problem.

**Comment by smvv** [comment]
FYI This was not a bug in the project that we used PyBison for at the time, because we defined the ``interactive`` attribute in the derived class: https://github.com/smvv/trs/blob/42bd415d96e12a53e9872e92ca6fa967851d0798/src/parser.py#L129

**Comment by arquer** [comment]
I assume you mean inserting it inside the "if not self.bisonEngineLibName:" clause?

> FYI This was not a bug in the project that we used PyBison for at the time, because we defined the interactive attribute in the derived class: https://github.com/smvv/trs/blob/42bd415d96e12a53e9872e92ca6fa967851d0798/src/parser.py#L129

Yes that is what I suspected.

**Comment by smvv** [comment]
I meant inside BisonParser.__init__(), and before constructing the ParserEngine object.

**Comment by smvv** [comment]
``BisonParser.__init__()``
