### ISSUE TITLE
Make to work on OS X

### ISSUE THREAD

**Issue by thisiscam** [smvv/pybison#5]
Hi,

I don't know how much this repo is still maintained, but I would really want to see this to work on OS X. I attempted a quick change in setup.py to allow OS X to be treated just like linux:
https://github.com/thisiscam/pybison/blob/mac/setup.py#L19

Then, somehow when I run the calculator example, I will get error when the shared library is being compiled by distutils:
<img width="1437" alt="screen shot 2016-06-14 at 9 16 03 pm" src="https://cloud.githubusercontent.com/assets/7684342/16067849/3baef1ee-3275-11e6-8739-ebd6ea4fe732.png">

So I made a hacky fix here: https://github.com/thisiscam/pybison/commit/533b5e070a822599e8dcdf33319dd996c3f27870#diff-665d1650a9ed6aa0aca6fad5f2ba1b41R540
(Maybe someone can tell me why distutils's Compiler works on linux but not on Mac? So I can make a more appropriate fix?)

Finally, the thing that I'm currently running into when I run the calc example:

> Segmentation fault: 11

A more detailed trace on gdb shows:
<img width="713" alt="screen shot 2016-06-14 at 9 19 25 pm" src="https://cloud.githubusercontent.com/assets/7684342/16067895/b619c13e-3275-11e6-8a89-22eaa6943490.png">

If anyone knows anything or is interested, I have a branch here https://github.com/thisiscam/pybison/tree/mac for my above attempts on OS X.

**Comment by smvv** [comment]
I've add some code to display distutils logging when 'verbose' is set. The logging shows which compiler commands are invoked to build the shared library. See also the updated example in `example/calc/`. Hope that that helps with debugging the problem.

**Comment by thisiscam** [comment]
Thanks @smvv , I did set verbose to true when I tried to debug and got the compiler commands -- this is how I know that I need to do 

> env.add_library('python') 

I suspect there might be some problem with the py_callback function, as after returning from it, PyErr_Occured in the generated tmp.bison.c's yyparse() will raise the above segfault; but I'm not sure.

**Comment by thisiscam** [comment]
Actually let me take the above back, if I just comment out the body of py_callback(and do "return NULL;"), I still get the same error. 

Now I begin to suspect that there's something really funky going on with my python -- though I did tried several installation setups on different OSXs and all chocked on that same error

**Comment by smvv** [comment]
Try setting a breakpoint in `py_callback` in the file `src/c/bison_callback.c`. If it returns null, PyErr_Occured() is raised and I guess it segfaults because of that.

Do you use Python 2 instead of 3?

**Comment by thisiscam** [comment]
Yes I'm using python2 for this

Yes, in the current code, py_callback does not return NULL, but still, PyErr_Occured is called in the generated yyparse, in a block of code that looks like

> ```
>       (yyval) = (*py_callback)(
>         py_parser, "input", 1, 2,
>         "input", (yyvsp[-1]),
>         "line", (yyvsp[0])
>         );
>       {
>         PyObject* obj = PyErr_Occurred();
>         if (obj) {
>           //yyerror("exception raised");
>           YYERROR;
>         }
>       }
> ```

I think the calling of PyErr_Occurred is intended(to check if handler raised any python exceptions), however, it's the calling of PyErr_Occurred that caused a segfault.. in other words, libpython caused this segfault somehow.

**Comment by smvv** [comment]
I'm not really sure at this moment what the problem is. I do not have Mac OS X to debug this further.

Btw, `bisondynlib_run` will load the parser's entry point `do_parse`. And `do_parse` is defined in your bison (*.y) file. Perhaps setting a breakpoint before https://github.com/smvv/pybison/blob/master/src/c/bisondynlib-linux.c#L71 and running "call PyErr_Occurred()" in gdb to see if it crashes before going into `do_parse` will help?

**Comment by thisiscam** [comment]
Very interestingly, calling PyErr_Occured from gdb returns NULL, even right before the call to PyErr_Occured is made in tmp.bison.c that raises the exception

**Comment by thisiscam** [comment]
@smvv after some investigation, I got mine to work on OS X: turns out my patch is correct except the fact that distutils is picking up another libpython than the one linked by the running interpreter.

But I think this shows some very subtle issue, that I personally not sure how to deal with: could you briefly recall how libpython is linked during the phase of buildLibs? Specifically, I'm referring to https://github.com/thisiscam/pybison/blob/master/src/pyrex/bison_.pyx#L540, how is libpython linked?

Below is the command showing the linking on my ubuntu(which works but doesn't link libpython explicitly):

> cc -shared ./tmp.bison.o ./tmp.lex.o -o ./calc-parser.x86_64-linux-gnu.so

Below is the command showing the linking on my OS X, which works after this modification:

> cc -shared ./tmp.bison.o ./tmp.lex.o -L/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib -lpython2.7 -o ./calc-parser.so

Notice that I have to specify both -L the path and the -lpython2.7

==== EDIT ====
I think I have understood the above problem and I have created  a PR.

**Comment by smvv** [comment]
Thanks for the PR!
